aliases:
  - &attach_workspace
    attach_workspace:
      at: ~/
orbs:
  devops: narvar/devops@0.0.22
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:16.14.0
    working_directory: ~/test-retailer-website
    steps:
      - checkout
      - *attach_workspace
      - restore_cache:
          key: v1-node-{{ arch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-node-{{ arch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/test-retailer-website/node_modules
      - run: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - ./test-retailer-website/package.json
            - ./test-retailer-website/Dockerfile
            - ./test-retailer-website/node_modules
            - ./test-retailer-website/dist
            - ./test-retailer-website/public
  publish:
    executor: devops/master-gcp
    working_directory: ~/test-retailer-website
    steps:
      - *attach_workspace
      - setup_remote_docker
      - devops/gcp-docker-login
      - devops/artifactory-export:
          build-provider: GCP
      - devops/docker-build:
          image-name: test-retailer-website
      - devops/docker-push:
          image-name: test-retailer-website
  deploy:
    executor: devops/deployment-master-aws
    steps:
      - devops/deployment-login
      - devops/deployment-repos
      - devops/deployment-helm3:
          deployment-name: test-retailer-website
          namespace: data-services
          timeout: 2m

workflows:
  version: 2
  test_retailer_website_workflow:
    jobs:
      - build:
      - publish:
          context:
            - build
            - qa01
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy:
          name: DeployQA01
          context: qa01
          requires:
            - publish
          filters:
            branches:
              only: master
